const recordData = [
  [
    "The Score",
    [
      "Red Intro",
      "How Many Mics",
      "Ready Or Not",
      "Zealots",
      "The Beast",
      "Fu-Gee-La",
      "Family Business",
      "Killing Me Softly",
      "The Score",
      "The Mask",
      "Cowboys",
      "No Woman, No Cry",
      "Manifest / Outro",
      "Fu-Gee-La (Refugee Camp Remix)",
      "Fu-Gee-La (Sly & Robbie Mix)",
      "Mista Mista",
    ],
    "Hip Hop",
    "Fugees_-_The_Score.png",
    1996,
  ],
  [
    "Enter The Wu-Tang (36 Chambers)",
    [
      "Bring Da Ruckus",
      "Shame On A Nigga",
      "Clan In Da Front",
      "Wu-Tang: 7th Chamber",
      "Can It Be All So Simple",
      "Protect Ya Neck (Intermission)",
      "Wu-Tang Sword",
      "Da Mystery Of Chessboxin'",
      "Wu-Tang Clan Ain't Nuthing Ta F' Wit",
      "C.R.E.A.M.",
      "Method Man",
      "Tearz",
      "Wu-Tang: 7th Chamber - Part II",
      "Conclusion",
    ],
    "Hip Hop",
    "Enter The Wu-Tang (36 Chambers).jpeg",
    1993,
  ],
  [
    "The Low End Theory",
    [
      "Excursions",
      "Buggin' Out",
      "Rap Promoter",
      "Butter",
      "Verses from the Abstract",
      "Show Business",
      "Vibes and Stuff",
      "The Infamous Date Rape",
      "Check the Rhime",
      "Everything Is Fair",
      "Jazz (We've Got)",
      "Skypager",
      "What?",
      "Scenario",
    ],
    "Hip Hop",
    "low_end_theory.jpeg",
    1991,
  ],
  [
    "Black Sunday",
    [
      "I Wanna Get High",
      "I Ain't Goin' Out Like That",
      "Insane in the Brain",
      "When the Sh-- Goes Down",
      "Lick a Shot",
      "Cock the Hammer",
      "Lock Down (Interlude)",
      "3 Lil' Putos",
      "Legalize It (Interlude)",
      "Hits from the Bong",
      "What Go Around Come Around, Kid",
      "A to the K",
      "Hand on the Glock",
      "Break 'Em Off Some",
    ],
    "Hip Hop",
    "black_sunday.jpg",
    1993,
  ],
  [
    "Doggystyle",
    [
      "Bathtub",
      "G Funk Intro",
      "Gin and Juice",
      "W Balls",
      "Tha Shiznit",
      "Domino Intro",
      "Lodi Dodi",
      "Murder Was the Case (Death After Visualizing Eternity)",
      "Serial Killa",
      "Who Am I (What's My Name)?",
      "For All My N---- and B----",
      "Ain't No Fun (If the Homies Can't Have None)",
      "Doggy Dogg World",
      "Gz and Hustlas",
      "Pump Pump",
    ],
    "Hip Hop",
    "doggystyle.jpg",
    1993,
  ],
  [
    "The Infamous",
    [
      "The Start of Your Ending (41st Side)",
      "The Infamous Prelude",
      "Survival of the Fittest",
      "Eye for a Eye (Your Beef Is Mines) (featuring Nas and Raekwon)",
      "Just Step Prelude",
      "Give Up the Goods (Just Step) (featuring Big Noyd)",
      "Temperature's Rising",
      "Up North Trip",
      "Trife Life",
      "Q.U. - Hectic",
      "Right Back at You (featuring Ghostface Killah, Raekwon, and Big Noyd)",
      "The Grave Prelude",
      "Cradle to the Grave",
      "Drink Away the Pain (Situations) (featuring Q-Tip)",
      "Shook Ones, Part II",
      "Party Over (featuring Big Noyd)",
    ],
    "Hip Hop",
    "the_infamous.jpeg",
    1995,
  ],
  [
    "Ready to Die",
    [
      "Intro",
      "Things Done Changed",
      "Gimme the Loot",
      "Machine Gun Funk",
      "Warning",
      "Ready to Die",
      "One More Chance",
      "Fuck Me (Interlude)",
      "The What (featuring Method Man)",
      "Juicy",
      "Everyday Struggle",
      "Me & My Bitch",
      "Big Poppa",
      "Respect",
      "Friend of Mine",
      "Unbelievable",
      "Suicidal Thoughts",
    ],
    "Hip Hop",
    "Ready_To_Die.jpeg",
    1994,
  ],
  [
    "Aquemini",
    [
      "Hold On, Be Strong",
      "Return of the 'G'",
      "Rosa Parks",
      "Skew It on the Bar-B (featuring Raekwon)",
      "Aquemini",
      "Synthesizer (featuring George Clinton)",
      "Slump",
      "West Savannah",
      "Da Art of Storytellin' (Part 1)",
      "Da Art of Storytellin' (Part 2)",
      "Mamacita (featuring Masada & Witchdoctor)",
      "SpottieOttieDopaliscious",
      "Y'all Scared (featuring T-Mo, Big Gipp & Khujo)",
      "Nathaniel",
      "Liberation (featuring Cee-Lo)",
    ],
    "Hip Hop",
    "AqueminiOutKast.jpeg",
    1998,
  ],
  [
    "The Miseducation of Lauryn Hill",
    [
      "Intro",
      "Lost Ones",
      "Ex-Factor",
      "To Zion (featuring Carlos Santana)",
      "Doo Wop (That Thing)",
      "Superstar",
      "Final Hour",
      "When It Hurts So Bad",
      "I Used to Love Him (featuring Mary J. Blige)",
      "Forgive Them Father",
      "Every Ghetto, Every City",
      "Nothing Even Matters (featuring D'Angelo)",
      "Everything Is Everything",
      "The Miseducation of Lauryn Hill",
      "Can't Take My Eyes Off You",
      "Tell Him",
    ],
    "Hip Hop",
    "public/images/themiseducationoflaurynhill.jpeg",
    1998,
  ],
  [
    "Highway 61 Revisited",
    [
      "Like a Rolling Stone",
      "Tombstone Blues",
      "It Takes a Lot to Laugh, It Takes a Train to Cry",
      "From a Buick 6",
      "Ballad of a Thin Man",

      "Queen Jane Approximately",
      "Highway 61 Revisited",
      "Just Like Tom Thumb's Blues",
      "Desolation Row",
    ],
    "Folk",
    "Bob_Dylan_-_Highway_61_Revisited.jpeg",
    1965,
  ],
  [
    "Blue",
    [
      "All I Want",
      "My Old Man",
      "Little Green",
      "Carey",
      "Blue",
      "California",
      "This Flight Tonight",
      "River",
      "A Case of You",
      "The Last Time I Saw Richard",
    ],
    "Folk",
    "Bluealbumcover.jpeg",
    1971,
  ],
  [
    "Sweet Baby James",
    [
      "Sweet Baby James",
      "Lo and Behold",
      "Sunny Skies",
      "Steamroller Blues",
      "Country Road",
      "Oh, Susannah",
      "Fire and Rain",
      "Blossom",
      "Anywhere Like Heaven",
      "Oh Baby, Don't You Loose Your Lip on Me",
      "Suite for 20 G",
    ],
    "Folk",
    "James_Taylor_-_Sweet_Baby_James.jpeg",
    1970,
  ],
  [
    "Bridge Over Troubled Water",
    [
      "Bridge over Troubled Water",
      "El Condor Pasa (If I Could)",
      "Cecilia",
      "Keep the Customer Satisfied",
      "So Long, Frank Lloyd Wright",
      "The Boxer",
      "Baby Driver",
      "The Only Living Boy in New York",
      "Why Don't You Write Me",
      "Bye Bye Love",
      "Song for the Asking",
    ],
    "Folk",
    "Simon_and_Garfunkel,_Bridge_over_Troubled_Water_(1970).png",
    1970,
  ],
  [
    "Kind of Blue",
    [
      "So What",
      "Freddie Freeloader",
      "Blue in Green",
      "All Blues",
      "Flamenco Sketches",
    ],
    "Jazz",
    "MilesDavisKindofBlue.jpeg",
    1959,
  ],
  [
    "Ella Fitzgerald Sings the Cole Porter Song Book",
    [
      "All Through the Night",
      "Anything Goes",
      "Miss Otis Regrets",
      "Too Darn Hot",
      "In the Still of the Night",
      "I Get a Kick Out of You",
      "Do I Love You?",
      "Always True to You in My Fashion",
    ],
    "Jazz",
    "Ellaportersongbook.jpeg",
    1956,
  ],
  [
    "Live at the Apollo",
    [
      "Introduction to James Brown and The Famous Flames",
      "I'll Go Crazy",
      "Try Me",
      "Think",
      "I Don't Mind",
      "Lost Someone",
      "Medley: Please, Please, Please/You've Got the Power/I Found Someone/Why Do You D",
    ],
    "Funk and Soul",
    "James_Brown-Live_at_the_Apollo_(album_cover).jpeg",
    1963,
  ],
  [
    "Songs in the Key of Life",
    [
      "Love's in Need of Love Today",
      "Have a Talk with God",
      "Village Ghetto Land",
      "Contusion",
      "Sir Duke",
      "I Wish",
      "Knocks Me Off My Feet",
      "Pastime Paradise",
      "Summer Soft",
      "Ordinary Pain",
      "Isn't She Lovely",
      "Joy Inside My Tears",
      "Black Man",
      "Ngiculela - Es Una Historia - I Am Singing",
      "If It's Magic",
      "As",
      "Another Star",
      "Saturn",
      "Ebony Eyes",
      "All Day Sucker",
      "Easy Goin' Evening (My Mama's Call)",
    ],
    "Funk and Soul",
    "Songs_in_the_key_of_life.jpeg",
    1976,
  ],
  [
    "What's Going On",
    [
      "What's Going On",
      "What's Happening Brother",
      "Flyin' High (In the Friendly Sky)",
      "Save the Children",
      "God Is Love",
      "Mercy Mercy Me (The Ecology)",
      "Right On",
      "Wholy Holy",
      "Inner City Blues (Make Me Wanna Holler)",
    ],
    "Funk and Soul",
    "MarvinGayeWhat'sGoingOnalbumcover.jpeg",
    1971,
  ],
  [
    "Lady Soul",
    [
      "Chain of Fools",
      "Money",
      "People Get Ready",
      "Niki Hoeky",
      "(You Make Me Feel Like) A Natural Woman",
      "(Sweet Sweet Baby) Since You've Been Gone",
      "Good to Me As I Am To You",
      "Come Back Baby",
      "Groovin'",
      "Ain't No Way",
    ],
    "Funk and Soul",
    "ArethaFranklinLadySoul.jpeg",
    1968,
  ],
  [
    "Gratitude",
    [
      "Introduction by MC Perry Jones",
      "Africano / Power",
      "Yearnin' Learnin'",
      "Devotion",
      "Sun Goddess",
      "Reasons",
      "Sing a Song",
      "Can't Hide Love",
      "Nfant",
      "Brazilian Rhyme (aka Ponta de Areia)",
      "Beijo (Interlude)",
      "Zanzibar",
    ],
    "Funk and Soul",
    "Earth,_Wind_&_Fire_-_Gratitude.jpeg",
    1975,
  ],
  [
    "Purple Rain",
    [
      "Let's Go Crazy",
      "Take Me with U",
      "The Beautiful Ones",
      "Computer Blue",
      "Darling Nikki",
      "When Doves Cry",
      "I Would Die 4 U",
      "Baby I'm a Star",
      "Purple Rain",
    ],
    "Funk and Soul",
    "Princepurplerain.jpeg",
    1984,
  ],
  [
    "Superfly",
    [
      "Little Child Runnin' Wild",
      "Pusherman",
      "Freddie's Dead",
      "Junkie Chase (instrumental)",
      "Give Me Your Love (Love Song)",
      "Eddie You Should Know Better",
      "No Thing on Me (Cocaine Song)",
      "Think (instrumental)",
      "Superfly",
    ],
    "Funk and Soul",
    "CurtisMayfieldSuperfly.jpeg",
    1972,
  ],
  [
    "Autobahn",
    [
      "Autobahn",
      "Kometenmelodie 1",
      "Kometenmelodie 2",
      "Mitternacht",
      "Morgenspaziergang",
    ],
    "Electronic",
    "Autobahn-kraftwerk-cover.jpeg",
    1974,
  ],
  [
    "Selected Ambient Works 85-92",
    [
      "Xtal",
      "Tha",
      "Pulsewidth",
      "Ageispolis",
      "i",
      "Green Calx",
      "Heliosphan",
      "We Are The Music Makers",
      "Schottkey 7th Path",
      "Ptolemy",
      "Hedphelym",
      "Delphium",
      "Actium",
    ],
    "Electronic",
    "Selected_Ambient_Works_85-92.png",
    1992,
  ],
  [
    "Mezzanine",
    [
      "Angel",
      "Risingson",
      "Teardrop",
      "Inertia Creeps",
      "Exchange",
      "Dissolved Girl",
      "Man Next Door",
      "Black Milk",
      "Mezzanine",
      "Group Four",
      "(Exchange)",
    ],
    "Electronic",
    "Massive_Attack_-_Mezzanine.png",
    1998,
  ],
  [
    "Violator",
    [
      "World in My Eyes",
      "Sweetest Perfection",
      "Personal Jesus",
      "Halo",
      "Waiting for the Night",
      "Enjoy the Silence",
      "Policy of Truth",
      "Blue Dress",
      "Clean",
    ],
    "Electronic",
    "Depeche_Mode_-_Violator.png",
    1990,
  ],
  [
    "Dummy",
    [
      "Mysterons",
      "Sour Times",
      "Strangers",
      "It Could Be Sweet",
      "Wandering Star",
      "Numb",
      "Roads",
      "Pedestal",
      "Biscuit",
      "Glory Box",
    ],
    "Electronic",
    "Portishead_-_Dummy.png",
    1994,
  ],
  [
    "Music for Airports",
    ["1/1", "2/1", "1/2", "2/2"],
    "Electronic",
    "Music_for_Airports.jpeg",
    1978,
  ],
  [
    "Abbey Road",
    [
      "Come Together",
      "Something",
      "Maxwell's Silver Hammer",
      "Oh! Darling",
      "Octopus's Garden",
      "I Want You (She's So Heavy)",
      "Here Comes the Sun",
      "Because",
      "You Never Give Me Your Money",
      "Sun King",
      "Mean Mr. Mustard",
      "Polythene Pam",
      "She Came in Through the Bathroom Window",
      "Golden Slumbers",
      "Carry That Weight",
      "The End",
      "Her Majesty",
    ],
    "Rock",
    "Beatles_-_Abbey_Road.jpeg",
    1969,
  ],
  [
    "Exile on Main St.",
    [
      "Rocks Off",
      "Rip This Joint",
      "Shake Your Hips",
      "Casino Boogie",
      "Tumbling Dice",
      "Sweet Virginia",
      "Torn and Frayed",
      "Sweet Black Angel",
      "Loving Cup",
      "Happy",
      "Turd on the Run",
      "Ventilator Blues",
      "I Just Want to See His Face",
      "Let It Loose",
      "All Down the Line",
      "Stop Breaking Down",
      "Shine a Light",
      "Soul Survivor",
    ],
    "Rock",
    "ExileMainSt.jpeg",
    1972,
  ],
  [
    "Rumours",
    [
      "Second Hand News",
      "Dreams",
      "Never Going Back Again",
      "Don't Stop",
      "Go Your Own Way",
      "Songbird",
      "The Chain",
      "You Make Loving Fun",
      "I Don't Want to Know",
      "Oh Daddy",
      "Gold Dust Woman",
    ],
    "Rock",
    "FMacRumours.png",
    1977,
  ],
  [
    "Led Zeppelin IV",
    [
      "Black Dog",
      "Rock and Roll",
      "The Battle of Evermore",
      "Stairway to Heaven",
      "Misty Mountain Hop",
      "Four Sticks",
      "Going to California",
      "When the Levee Breaks",
    ],
    "Rock",
    "Led_Zeppelin_-_Led_Zeppelin_IV.jpeg",
    1971,
  ],
  [
    "Are You Experienced",
    [
      "Purple Haze",
      "Manic Depression",
      "Hey Joe",
      "Love or Confusion",
      "May This Be Love",
      "I Don't Live Today",
      "The Wind Cries Mary",
      "Fire",
      "Third Stone from the Sun",
      "Foxey Lady",
      "Are You Experienced",
    ],
    "Rock",
    "AreyouexpUK.jpeg",
    1967,
  ],
  [
    "A Night at the Opera",
    [
      "Death on Two Legs (Dedicated to...)",
      "Lazing on a Sunday Afternoon",
      "I'm in Love with My Car",
      "You're My Best Friend",
      "'39",
      "Sweet Lady",
      "Seaside Rendezvous",
      "The Prophet's Song",
      "Love of My Life",
      "Good Company",
      "Bohemian Rhapsody",
      "God Save the Queen",
    ],
    "Rock",
    "Queen_A_Night_At_The_Opera.png",
    1975,
  ],
  [
    "Disraeli Gears",
    [
      "Strange Brew",
      "Sunshine of Your Love",
      "World of Pain",
      "Dance the Night Away",
      "Blue Condition",
      "Tales of Brave Ulysses",
      "SWLABR",
      "We're Going Wrong",
      "Outside Woman Blues",
      "Take It Back",
      "Mother's Lament",
    ],
    "Rock",
    "DisraeliGears.jpeg",
    1967,
  ],
];

module.exports = recordData;
